//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace WindowsFormsApplicationPruebaPDF.wsgeneracioncomprobantes85 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSGeneracionComprobantesSoap", Namespace="http://tempuri.org/")]
    public partial class WSGeneracionComprobantes : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SGenerarComprobanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SGenerarComprobanterutaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerarComprobanterutaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSGeneracionComprobantes() {
            this.Url = global::WindowsFormsApplicationPruebaPDF.Properties.Settings.Default.WindowsFormsApplicationPruebaPDF_wsgeneracioncomprobantes85_WSGeneracionComprobantes;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SGenerarComprobanteCompletedEventHandler SGenerarComprobanteCompleted;
        
        /// <remarks/>
        public event SGenerarComprobanterutaCompletedEventHandler SGenerarComprobanterutaCompleted;
        
        /// <remarks/>
        public event GenerarComprobanterutaCompletedEventHandler GenerarComprobanterutaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SGenerarComprobante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SGenerarComprobante(string sNumeroComprobante, bool escopia) {
            object[] results = this.Invoke("SGenerarComprobante", new object[] {
                        sNumeroComprobante,
                        escopia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SGenerarComprobanteAsync(string sNumeroComprobante, bool escopia) {
            this.SGenerarComprobanteAsync(sNumeroComprobante, escopia, null);
        }
        
        /// <remarks/>
        public void SGenerarComprobanteAsync(string sNumeroComprobante, bool escopia, object userState) {
            if ((this.SGenerarComprobanteOperationCompleted == null)) {
                this.SGenerarComprobanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSGenerarComprobanteOperationCompleted);
            }
            this.InvokeAsync("SGenerarComprobante", new object[] {
                        sNumeroComprobante,
                        escopia}, this.SGenerarComprobanteOperationCompleted, userState);
        }
        
        private void OnSGenerarComprobanteOperationCompleted(object arg) {
            if ((this.SGenerarComprobanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SGenerarComprobanteCompleted(this, new SGenerarComprobanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SGenerarComprobanteruta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SGenerarComprobanteruta(string sNumeroComprobante, string sruta) {
            object[] results = this.Invoke("SGenerarComprobanteruta", new object[] {
                        sNumeroComprobante,
                        sruta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SGenerarComprobanterutaAsync(string sNumeroComprobante, string sruta) {
            this.SGenerarComprobanterutaAsync(sNumeroComprobante, sruta, null);
        }
        
        /// <remarks/>
        public void SGenerarComprobanterutaAsync(string sNumeroComprobante, string sruta, object userState) {
            if ((this.SGenerarComprobanterutaOperationCompleted == null)) {
                this.SGenerarComprobanterutaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSGenerarComprobanterutaOperationCompleted);
            }
            this.InvokeAsync("SGenerarComprobanteruta", new object[] {
                        sNumeroComprobante,
                        sruta}, this.SGenerarComprobanterutaOperationCompleted, userState);
        }
        
        private void OnSGenerarComprobanterutaOperationCompleted(object arg) {
            if ((this.SGenerarComprobanterutaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SGenerarComprobanterutaCompleted(this, new SGenerarComprobanterutaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GenerarComprobanteruta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GenerarComprobanteruta(string sNumeroComprobante, string sruta, string prueba) {
            object[] results = this.Invoke("GenerarComprobanteruta", new object[] {
                        sNumeroComprobante,
                        sruta,
                        prueba});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GenerarComprobanterutaAsync(string sNumeroComprobante, string sruta, string prueba) {
            this.GenerarComprobanterutaAsync(sNumeroComprobante, sruta, prueba, null);
        }
        
        /// <remarks/>
        public void GenerarComprobanterutaAsync(string sNumeroComprobante, string sruta, string prueba, object userState) {
            if ((this.GenerarComprobanterutaOperationCompleted == null)) {
                this.GenerarComprobanterutaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerarComprobanterutaOperationCompleted);
            }
            this.InvokeAsync("GenerarComprobanteruta", new object[] {
                        sNumeroComprobante,
                        sruta,
                        prueba}, this.GenerarComprobanterutaOperationCompleted, userState);
        }
        
        private void OnGenerarComprobanterutaOperationCompleted(object arg) {
            if ((this.GenerarComprobanterutaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerarComprobanterutaCompleted(this, new GenerarComprobanterutaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SGenerarComprobanteCompletedEventHandler(object sender, SGenerarComprobanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SGenerarComprobanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SGenerarComprobanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SGenerarComprobanterutaCompletedEventHandler(object sender, SGenerarComprobanterutaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SGenerarComprobanterutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SGenerarComprobanterutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GenerarComprobanterutaCompletedEventHandler(object sender, GenerarComprobanterutaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerarComprobanterutaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerarComprobanterutaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591